### ISSUE TITLE
FileNotFoundError not available in python2

### ISSUE THREAD

**Issue by sieben** [kennethreitz/setup.py#26]
FileNotFoundError is not defined in python2

$ python setup.py publish
running publish
Removing previous builds…
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    'publish': PublishCommand,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 60, in run
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

**Comment by kennethreitz** [comment]
let's get this fixed

**Comment by kennethreitz** [comment]
What does FileNotFoundError inherit from? We can use it's base exception.

**Comment by sieben** [comment]
It inherits from OSError in Python2 and Python3

**Comment by sieben** [comment]
https://github.com/kennethreitz/setup.py/pull/27

**Comment by kennethreitz** [comment]
:+1:

**Comment by MaffooClock** [comment]
This problem is reintroduced nine months later in commit 81a9a65949bdf984f9a58426670d7e8c6f06a0df
